/**
 * Created by hea on 6/12/18.
 */


/*

export const constant ={
    server: 'http://localhost:5000',
    newsurl: 'https://newsapi.org/v2/top-headlines',
    newsapikey: '4f850ae6cf93486f8012540b62510ecb',
    country: {
        'Argentina': 'ar',
        'Australia': 'au',
        'Austria': 'at',
        'Belgium': 'be',
        'Brazil': 'br',
        'Bulgaria': 'bg',
        'Canada': 'ca',
        'China': 'cn',
        'Colombia': 'co',
        'Cuba': 'cu',
        'Czech Republic': 'cz',
        'Egypt': 'eg',
        'France': 'fr',
        'Germany': 'de',
        'Greece': 'gr',
        'China Hong Kong': 'hk',
        'Hungary': 'hu',
        'India': 'in',
        'Indonesia': 'id',
        'Ireland': 'ie',
        'Israel': 'il',
        'Italy': 'it',
        'Japan': 'jp',
        'Latvia': 'lv',
        'Lithuania': 'lt',
        'Malaysia': 'my',
        'Mexico': 'mx',
        'Morocco': 'ma',
        'Netherlands': 'nl',
        'New Zealand': 'nz',
        'Nigeria': 'ng',
        'Norway': 'no',
        'Philippines': 'ph',
        'Poland': 'pl',
        'Portugal': 'pt',
        'Romania': 'ro',
        'Russia': 'ru',
        'Saudi Arabia': 'sa',
        'Serbia': 'rs',
        'Singapore': 'sg',
        'Slovakia': 'sk',
        'Slovenia': 'si',
        'South Africa': 'za',
        'South Korea': 'kr',
        'Sweden': 'se',
        'Switzerland': 'ch',
        'China Taiwan': 'tw',
        'Thailand': 'th',
        'Turkey': 'tr',
        'UAE':'ae',
        'Ukraine': 'ua',
        'United Kingdom':'gb',
        'United States':'us',
        'Venuzuela':'ve'
    },
    category:{'Business':'business','Entertainment':'entertainment', 'General':'general', 'Health':'health', 'Sports':'sports', 'Technology':'technology'},
    emojiList: ['😀','😅','🙂','😚','😝','😔','🙁','😫','😭','😡','😱','🤥','😯','😵','😷','👌','👍','🤝','🐶','🐱','🐭','🐹','🐰','🦊','🐻','🐼','🐨','🐯','🐷']

};
*/

export const constant ={
    server: '',
    newsurl: 'https://newsapi.org/v2/top-headlines',
    newsapikey: '4f850ae6cf93486f8012540b62510ecb',
    country: {
        'Argentina': 'ar',
        'Australia': 'au',
        'Austria': 'at',
        'Belgium': 'be',
        'Brazil': 'br',
        'Bulgaria': 'bg',
        'Canada': 'ca',
        'China': 'cn',
        'Colombia': 'co',
        'Cuba': 'cu',
        'Czech Republic': 'cz',
        'Egypt': 'eg',
        'France': 'fr',
        'Germany': 'de',
        'Greece': 'gr',
        'China Hong Kong': 'hk',
        'Hungary': 'hu',
        'India': 'in',
        'Indonesia': 'id',
        'Ireland': 'ie',
        'Israel': 'il',
        'Italy': 'it',
        'Japan': 'jp',
        'Latvia': 'lv',
        'Lithuania': 'lt',
        'Malaysia': 'my',
        'Mexico': 'mx',
        'Morocco': 'ma',
        'Netherlands': 'nl',
        'New Zealand': 'nz',
        'Nigeria': 'ng',
        'Norway': 'no',
        'Philippines': 'ph',
        'Poland': 'pl',
        'Portugal': 'pt',
        'Romania': 'ro',
        'Russia': 'ru',
        'Saudi Arabia': 'sa',
        'Serbia': 'rs',
        'Singapore': 'sg',
        'Slovakia': 'sk',
        'Slovenia': 'si',
        'South Africa': 'za',
        'South Korea': 'kr',
        'Sweden': 'se',
        'Switzerland': 'ch',
        'China Taiwan': 'tw',
        'Thailand': 'th',
        'Turkey': 'tr',
        'UAE':'ae',
        'Ukraine': 'ua',
        'United Kingdom':'gb',
        'United States':'us',
        'Venuzuela':'ve'
    },
    category:{'Business':'business','Entertainment':'entertainment', 'General':'general', 'Health':'health', 'Sports':'sports', 'Technology':'technology'},
    emojiList: ['😀','😅','🙂','😚','😝','😔','🙁','😫','😭','😡','😱','🤥','😯','😵','😷','👌','👍','🤝','🐶','🐱','🐭','🐹','🐰','🦊','🐻','🐼','🐨','🐯','🐷']

};

